### ISSUE TITLE
ethcracker not compatible with wordlist files

### ISSUE THREAD

**Issue by losteth** [lexansoft/ethcracker#1]
Hello,

thank you for writing this tool!

Is it possible to use standard wordlists (newline seperated) with your tool?
I cannot find any option to do so.

Adding this feature would enable me to recover my password, since i have a long wordlist.

Thank you!

**Comment by lexansoft** [comment]
What do you mean by wordlists? Give me an example please.


Alexandre Naverniouk

**Comment by ethlost2** [comment]
Thank you for your fast response!

I have a file with many possible passwords, just like files that your tool generates with the '-dump' option. A so called wordlist.

Each line has one possible PW. So how can i get ethcracker to treat each line as a single password and try each one?

**Comment by lexansoft** [comment]
Git it. Let me some time.


Alexandre Naverniouk

**Comment by ethlost2** [comment]
Great, thank you!

**Comment by lexansoft** [comment]
1.10 supports -l flag. You can specify your wordlist file and the program will try every line from it.

**Comment by ethlost2** [comment]
Amazing, keep up your great work!
