### ISSUE TITLE
How to run a 'blank' 

### ISSUE THREAD

**Issue by AndyNormore** [lexansoft/ethcracker#10]
Using Pythrecover, you can run a password file like this:

("", "A", "B"),
("", "b", "c"),
("absolutely")
("", "sometimes")

By including this blank, you can achieve more possible variations. I can't remember if my password began with an A, or a B. But perhaps it was actually the lower case b. 

I'd like to run them all.

Currently, I don't know if EthCracker can do this. I think it's better software because of the multithreading. 

But I just can't get the same control as Pythrecover.

What do you think?

**Comment by lexansoft** [comment]
The blank is there by default. If you do not want it you can use ~a at the
beginning of the line. This means "always use some value from this line",
or in other words, do not use blank.


Alexandre Naverniouk

**Comment by AndyNormore** [comment]
Again, thank you for such a quick reply. Now I feel silly.

**Comment by AndyNormore** [comment]
Confirmed only minutes later, this is great. Thank you.
