### ISSUE TITLE
Speed: 20 Threads VS 1 Single Pythrecover

### ISSUE THREAD

**Issue by AndyNormore** [lexansoft/ethcracker#11]
Not really an issue, but I thought I'd ask here.

I'm running Pythrecover at the moment, which seems to be 1 single thread. It does however, MAX my CPU. That's good, right? Lots of power going there.

But, EthCracker can do 20 threads on my machine, and the CPU doesn't seem to increase too much.

So - Which is faster?

**Comment by lexansoft** [comment]
It only makes sense to use multithreading if you have multi-core.  For
example, if you have 4 cores, you can specify 3 threads. It speeds up the
process, but not too much, not 3 times.




Alexandre Naverniouk

**Comment by AndyNormore** [comment]
I see. So a few friends I'm in contact with who are doing the same, are running a Google Cloud Compute instance, for example.

We have selected 8 CPU cores.

So, should we run on

-threads 7 

What happens if we run on 

-threads 20

**Comment by lexansoft** [comment]
Those are in fact GoLang threads. They are virtual. You can specify 20, but
they will still share 8 physical cores. So, do not specify more than 8.

Usually, you use MAX-1 on the computer that you use for other things the
same time. If it is a dedicated box, you can max.


Alexandre Naverniouk

**Comment by AndyNormore** [comment]
Thank you very much. I'm running on my Alienware R17, and a Cloud Compute.

Well. Time to let this thing run for weeks now... Cheers. I'll be sure to leave you some Eth when I recover my 250!

**Comment by lexansoft** [comment]
Good luck!


Alexandre Naverniouk
