### ISSUE TITLE
GetFileAttributesEx src/ethcracker.go: System can't find specified path

### ISSUE THREAD

**Issue by Spartakkus** [lexansoft/ethcracker#12]
After doing all the preinstalls for Windows, If I open a cmd with administration permissions, I start here:

C:\WINDOWS\system32

From here, I run

go run src/ethcracker.go -pk C:\Users\spartakkus\Desktop\test\xxxxxx.txt -l C:\Users\spartakkus\Desktop\varpsw.txt -threads 4 

- xxxxxx.txt is my encrypted key file (I added .txt at the end to the original file)

- varpsw.txt is the text will all password possibilities, one by line

I get an error, that is:

GetFileAttributesEx src/ethcracker.go: System can't find specified path

What is happening? I've checked that both txt files are readable (if I put the path in a new window I see the txt content)

Thanks

**Comment by lexansoft** [comment]
In your line:

go run src/ethcracker.go ...

" src/ethcracker.go" should be the path to the ethcracker.go file. Change
it to the folder where you downloaded the source to.







Alexandre Naverniouk

**Comment by Spartakkus** [comment]
C:\Program Files\Git\ethcracker\src       ------> is where I have ethcracker.go

If I run:

C:\WINDOWS\system32>go run C:\Program Files\Git\ethcracker\src\ethcracker.go -pk C:\Users\spartakkus\Desktop\test\xxxxxxx.txt -l C:\Users\spartakkus\Desktop\varpsw.txt -threads 4

Now I get:

go run: no go files listed

what happens????? Thank you for the quickness

**Comment by lexansoft** [comment]
;)

\Program File has white space in it.

Put the path in quotes.


Alexandre Naverniouk

**Comment by Spartakkus** [comment]
Solved, running now. Thank you so much!
