### ISSUE TITLE
Question ethcracker

### ISSUE THREAD

**Issue by IvanM1993** [lexansoft/ethcracker#13]
good afternoon. Trying to recover the password for Ethereum wallet with Ethereum password cracker.  I got to the section to install Go Language. Complied with this section 
"Installing
Install Go Language

git clone https://github.com/lexansoft/ethcracker
cd ethcracker

go get github.com/ethereum/go-ethereum
go get github.com/pborman/uuid
go get golang.org/x/crypto/pbkdf2
go get golang.org/x/crypto/ripemd160
go get golang.org/x/crypto/scrypt
go get github.com/rjeczalik/notify"

This was followed by the folder ethcracker. And that the reference should be instead of "PATH_TO_FILE t PATH_TO_TEMPLATE_FILE "?? It refers UTC keystore file? Next, I do not understand what steps need to be done? Help, please. 

After I launched the following command. Then there is an error

C:\windows\system32>go run "C:\Users\...\ethcracker\src\ethcracker.go"
# _/C_/Users/..../ethcracker/src/accounts/keystore
C:\Users\....\ethcracker\src\accounts\keystore\keystore.go:114: cannot use ke
ystoreWallet literal (type *keystoreWallet) as type accounts.Wallet in assignmen
t:
        *keystoreWallet does not implement accounts.Wallet (wrong type for Statu
s method)
                have Status() string
                want Status() (string, error)
C:\Users\...\ethcracker\src\accounts\keystore\keystore.go:146: unknown field
 'Arrive' in struct literal of type accounts.WalletEvent
C:\Users\....\ethcracker\src\accounts\keystore\keystore.go:153: cannot use wa
llet (type *keystoreWallet) as type accounts.Wallet in field value:
        *keystoreWallet does not implement accounts.Wallet (wrong type for Statu
s method)
                have Status() string
                want Status() (string, error)
C:\Users\....\ethcracker\src\accounts\keystore\keystore.go:153: unknown field
 'Arrive' in struct literal of type accounts.WalletEvent
C:\Users\....\ethcracker\src\accounts\keystore\keystore.go:154: cannot use wa
llet (type *keystoreWallet) as type accounts.Wallet in append:
        *keystoreWallet does not implement accounts.Wallet (wrong type for Statu
s method)
                have Status() string
                want Status() (string, error)
C:\Users\.....\ethcracker\src\accounts\keystore\keystore.go:166: unknown field
 'Arrive' in struct literal of type accounts.WalletEvent
Am I doing something wrong?

**Comment by lexansoft** [comment]
Yes. PATH_TO_FILE should be path to your private kay file.
PATH_TO_TEMPLATE_FILE
- path to the text file with all your possible password substrings.


Alexandre Naverniouk

**Comment by IvanM1993** [comment]
Thanks for the reply. So, I have the UTC file to add format .txt? and specify this path?

**Comment by lexansoft** [comment]
Do not add anything. Just use the path as it is with -pk key.

-pk PATH_TO_FILE


Then create a new text file - template. And use its path with -t key :

-t PATH_TO_TEMPLATE_FILE




Alexandre Naverniouk

**Comment by IvanM1993** [comment]
I started so to see how well I'm doing? C:\windows\system32>go run "C:\Users\....\ethcracker\src\ethcracker.go" 
-pk "C:\Users\....\AppData\Roaming\Ethereum\keystore\...name-key....." -threads 4
I did the following.. But I don't know gives the same error, the error in the first message.

**Comment by IvanM1993** [comment]
please help.

 I started so to see how well I'm doing? C:\windows\system32>go run "C:\Users....\ethcracker\src\ethcracker.go"
-pk "C:\Users....\AppData\Roaming\Ethereum\keystore...name-key....." -threads 4
I did the following.. But I don't know gives the same error, the error in the first message.
What is the pattern not understand what to create? Sorry for the misunderstanding
the template should be empty?

**Comment by lexansoft** [comment]
The template is the file that determines what password variants will be
tried. For example, if you create template like this:


cat dog
1 2


Then the program will try all the combinations like:

cat
dog
1
2
cat1
1cat
cat2
2cat
dog1
1dog
dog2
2dog

Please refer to the readme file for more information.



Alexandre Naverniouk

**Comment by IvanM1993** [comment]
why it is not working. Gives an error at startup ethcracker.go. I'm pointing all the way right. 

# _/C_/Users/...../ethcracker/src/accounts/keystore
C:\Users\.....\ethcracker\src\accounts\keystore\keystore.go:114: cannot use ke
ystoreWallet literal (type *keystoreWallet) as type accounts.Wallet in assignmen
t:
        *keystoreWallet does not implement accounts.Wallet (wrong type for Statu
s method)
                have Status() string
                want Status() (string, error)
C:\Users\.....\ethcracker\src\accounts\keystore\keystore.go:146: unknown field
 'Arrive' in struct literal of type accounts.WalletEvent
C:\Users\....\ethcracker\src\accounts\keystore\keystore.go:153: cannot use wa
llet (type *keystoreWallet) as type accounts.Wallet in field value:
        *keystoreWallet does not implement accounts.Wallet (wrong type for Statu
s method)
                have Status() string
                want Status() (string, error)
C:\Users\.....\ethcracker\src\accounts\keystore\keystore.go:153: unknown field
 'Arrive' in struct literal of type accounts.WalletEvent
C:\Users\....\ethcracker\src\accounts\keystore\keystore.go:154: cannot use wa
llet (type *keystoreWallet) as type accounts.Wallet in append:
        *keystoreWallet does not implement accounts.Wallet (wrong type for Statu
s method)
                have Status() string
                want Status() (string, error)
C:\Users\....\ethcracker\src\accounts\keystore\keystore.go:166: unknown field
 'Arrive' in struct literal of type accounts.WalletEvent

Here is the path to the file, did everything according to this link 

https://github.com/lexansoft/ethcracker/blob/master/README.md

go run "C:\Users\....\ethcracker\src\ethcracker.go" -pk "
C:\Users\.....\AppData\Roaming\Ethereum\keystore\xxxxxxx(name key)" -l "C:\Users\.....\AppData\R
oaming\Ethereum\varpsw.txt" -threads 4

https://github.com/lexansoft/ethcracker/issues/12

And looked here.

**Comment by IvanM1993** [comment]
why is not working ethcracker.go. please help. I do not want to lose ether.

**Comment by lexansoft** [comment]
Version 2.15 is committed. To use it, please update the ethereum-go files.
