### ISSUE TITLE
Parenthesis? Is this an issue for EthCracker?

### ISSUE THREAD

**Issue by anormore** [lexansoft/ethcracker#18]
Recently it has come to light that if you had used a parenthesis in your password, it would not work.

Presale wallet.

Is this an issue for Ethcracker?

**Comment by lexansoft** [comment]
hmm... it should work in the template file no problem


Alexandre Naverniouk

**Comment by anormore** [comment]
Hi @lexansoft, can you view this thread? 

https://github.com/ethereum/mist/issues/2411

The Ethereum wallet is unable to import wallets due to special characters. I want to know if this problem would affect EthCracker?

Does EthCracker use its' own libraries for cracking Ethereum? Or is it using some library from Geth? Is it possible that EthCracker also shares this problem of invalid characters not opening wallets?

**Comment by anormore** [comment]
Closing this issue in favor of #23
