### ISSUE TITLE
Request: -log logfile.txt -range 0% 50%

### ISSUE THREAD

**Issue by anormore** [lexansoft/ethcracker#19]
Just thought I'd open a ticket here, I'm going to try and write this myself.

I've got multiple computers running, and would like to utilize them. Some times they reboot, and I have no way to know where it left off. Annoying. 

So how about a log output?

Additionally, can we set the script to start from 0% to 50%, then another system to run from 50% to 100%.

This can be extended easily from 0-10%, 10-20%, 20-30% and so forth, to multi-task the entire process.

**Comment by lexansoft** [comment]
The terminal actually keeps the output, so after restarting you can
continue the cracking.


Alexandre Naverniouk

**Comment by anormore** [comment]
I'm running on Windows, so after an unexpected reboot ... it's gone!

**Comment by anormore** [comment]
can we set the script to start from 0% to 50%, then another system to run from 50% to 100%.

**Comment by lexansoft** [comment]
Yes, you can simply specify -start_from 50%




Alexandre Naverniouk
