### ISSUE TITLE
ethcracker runs and  immediately generates garbage output?

### ISSUE THREAD

**Issue by jsgithub2018** [lexansoft/ethcracker#25]
Hi,

When I run "ethcracker -pk ~\mywallet.txt -t ~\mytemplate.txt -threads 4"  it immediately generates an "ethcracker" output file that is largely unreadable (binary/hex) about 6MB in size.

I assume the output should contain my password if everything worked ok.  Is there a sample output (A test wallet and template would be great).  I also assume it should take some time to process before giving an output, so this seems more like an error output to me.

Any idea what I'm doing wrong?

Thanks,
Jeff

**Comment by lexansoft** [comment]
Hmm... can I see at least the beginning of the output?


Alexandre Naverniouk

**Comment by jsgithub2018** [comment]
Hi,

See attached (1st 40 lines of output file). 
[ethcracker4Alex.txt](https://github.com/lexansoft/ethcracker/files/1740757/ethcracker4Alex.txt)

I simply renamed my ethereum keystore file to 'mywallet.txt'.   I do have a parenthesis and other special characters in my template (I saw a reference that parenthesis may cause a problem with ethcracker?).   But I know the password I'm trying to recover had parenthesis in it....

Thanks,
Jeff
[ethcracker4Alex.txt](https://github.com/lexansoft/ethcracker/files/1740761/ethcracker4Alex.txt)

**Comment by lexansoft** [comment]
parenthesis should not be a problem


Alexandre Naverniouk

**Comment by jsgithub2018** [comment]
Any ideas what may be wrong in my case?  Can you provide a test wallet and template?

**Comment by jsgithub2018** [comment]
Nevermind.  I'm an idiot.  Was just following the readme directly but I'm on a windows box, so I need to use the ethcracker211.exe as the executable, not ethcracker by itself.  Sorry for the fuss.  Program works great on my test wallet.  Now I need lots of processing time to figure out my real wallet password.

noob idiot signing off
