### ISSUE TITLE
Question about template

### ISSUE THREAD

**Issue by jsgithub2018** [lexansoft/ethcracker#26]
Hi again,

It's not clear to me how the rows and columns in the template affect the program.

How is this template:
a b c

different than this
a
b
c

?
Thanks,
Jeff

**Comment by lexansoft** [comment]
The first one will produce only 3 combinations.

a
b
c

The second will have all the permutations like:

a
ab
ac
abc
acb
b
ba
ba
bac
and so on...


Alexandre Naverniouk

**Comment by jsgithub2018** [comment]
Thanks
