### ISSUE TITLE
Number of Threads?

### ISSUE THREAD

**Issue by jsgithub2018** [lexansoft/ethcracker#27]
How does number of threads impact the time to process?  How do I know my optimal number of threads to use?  Is it always 4?

Thanks again

**Comment by lexansoft** [comment]
To be honest it effects the speed not so much. It depends on the number of
physical cores you have in your system. Let's lay if you have 8 cores, you
can set the number of threads to 6 or 7.  The bigger number will, in fact,
slow down the speed.


Alexandre Naverniouk

**Comment by jsgithub2018** [comment]
Thanks.  Another question if you don't mind.  Why does it sometimes show 'skipped'?  This means some valid combination was not tried?

TH1-> 20916/109601 19% Skipped: 3074 Left: 0 years 0 days 5 hours 56 minutes

**Comment by lexansoft** [comment]
It skips only if a combination is shorter than minimum length or longer than maximum length.                                                                                                                                                                        Sent via the BlackBerry Hub for Android                                                                                                                                                                           From: notifications@github.comSent: February 22, 2018 6:56 AMTo: ethcracker@noreply.github.comReply-to: reply@reply.github.comCc: alexn@lexansoft.com; comment@noreply.github.comSubject: Re: [lexansoft/ethcracker] Number of Threads? (#27)  Thanks.  Another question if you don't mind.  Why does it sometimes show 'skipped'?  This means some valid combination was not tried?
TH1-> 20916/109601 19% Skipped: 3074 Left: 0 years 0 days 5 hours 56 minutes

**Comment by jsgithub2018** [comment]
thanks again
