### ISSUE TITLE
£ sign incorrectly appears as a different character (square within a square) in attempts...

### ISSUE THREAD

**Issue by DavidMc0** [lexansoft/ethcracker#3]
This software is great, but I have an issue where the £ symbol appears as a square within a square symbol, and I'm not sure if it is being processed correctly, or if the £ symbol is being substituted for another when the password attempts are being made.  I have a UK layout keyboard.

Hope there's an easy fix for this, whether it's not being processed correctly, or if it's just how the text appears in CMD window.

Thanks.

**Comment by lexansoft** [comment]
Sorry for the long delay.

I tried £ in the template file and it works and shows correctly. (on mac)

What platform you are on?




Alexandre Naverniouk

**Comment by DavidMc0** [comment]
Thanks for your reply and for trying this out.

I'm using Windows 10.

I've attached an image showing how it looks when I attempt £-£-£-£-£

![image](https://cloud.githubusercontent.com/assets/6334410/17513796/ff6a10aa-5e26-11e6-90cc-7f9653c8a219.png)

Thanks,

David

**Comment by lexansoft** [comment]
I think this is just the way your system font shows the character in CLI.
It should not be a problem.


Alexandre Naverniouk
