### ISSUE TITLE
Runtime error: index out of range

### ISSUE THREAD

**Issue by Mukhametvaleev** [lexansoft/ethcracker#4]
Then i run 

> go run src/ethcracker.go -pk UTC--20... -t passwords.txt -threads 4

I've got a runtime error "index out of range"

Console log:

> ------------------------------------------------
> Ethereum Password Cracker v2.0
> Author: @AlexNa 
> ------------------------------------------------
> Private Key File: UTC--2017-04-...
> Template File: passwords.txt
> Verbosity: 1
> Minimum password length: 8
> Maximum password length: 20
> Number of threads: 4
> Presale file: false
> Keep order: false
> Report every : 1 combination
> Key file version: v3
> panic: runtime error: index out of range
> 
> goroutine 1 [running]:
> main.main()
> 	/Users/andrei/Downloads/ethcracker-master/src/ethcracker.go:179 +0xcc5
> exit status 2
>

**Comment by lexansoft** [comment]
You probably have some empty lines in the template file.

**Comment by Mukhametvaleev** [comment]
I opened "passwords.txt" with macOS textEdit app and it's looks fine, but if i do "cat passwords.txt" in terminal there is a many garbage (it's a textEdit view setting). Saving file as plain text solved the problem! Thanks
