### ISSUE TITLE
invalid character 'U' looking for beginning of value

### ISSUE THREAD

**Issue by Jnkz** [lexansoft/ethcracker#5]
Hello, i tried to run it with my wallet. I created it one year ago on myetherwallet.com, and my privatekey is starting with an U.

On "panic", i got the message : "invalid character 'U' looking for beginning of value

What i have to do? Is ethcracker able to crack my wallet?

Thank's for your help, sorry for my english

**Comment by lexansoft** [comment]
It looks like the JSON format of the file is broken. Could you please check
if it is a plain text file, not unicode?


Alexandre Naverniouk

**Comment by Jnkz** [comment]
Hey back, thank's for you fast answer.

 I'm not confortable with all oh that and i don't understand what i have to check. When you talk about JSON format, you're talking about my private key JSON format or the script one? 

Because, on my script, i replace it like that that : go run src/ethcracker.go -pk C:\Users\Jnkz\Desktop\privatekey.txt -t C:\Users\Jnkz\Desktop\dov.txt -threads 4        (privatekey is the name of the txt where i pasted my private key starting by the 'U' , dov the template file)

Did i understand something wrong? I have to use directly my JSON file directory on the script?

**Comment by lexansoft** [comment]
The file C:\Users\Jnkz\Desktop\privatekey.txt should be your private key
file. The whole JSON file with all the parameters.


Alexandre Naverniouk

**Comment by Jnkz** [comment]
Ok ok, so this time i opened my JSON file with txt, i copy/paste all of the content on privatekey, and i tried to run this. No more 'U' error when i run ' go run src/ethcracker.go -pk C:\Users\Jnkz\Desktop\privatekey -Encrypted.json -t C:\Users\Jnkz\Desktop\dov -threads 4 ' , now there is something else happening : 

'flag provided but not defined : -Encrypted.json 
Usage of C:\Users\...\command-line-arguments\_obj\exe\ethcracker.exe
-dump string Just output all the possible variants
...'  
Followed by all the others (-presale, -pk string...)

I have to complete all that parameters on my private key file? 
Thank's for helping me so much, and sorry to making you loosing your time. Be sure i'll don't forget to donate if i can recover my wallet

**Comment by lexansoft** [comment]
Remove '-' in front of -Encrypted.json


Alexandre Naverniouk

**Comment by Jnkz** [comment]
Now 'panic : open C:\Users\myname\Desktop\privatekey : le fichier spécifié est introuvable'   which mean the file is not found 

Must be easier if i was able to show you that. There is a way?

**Comment by lexansoft** [comment]
Most likely C:\Users\myname\Desktop\privatekey has some extension. May be
C:\Users\myname\Desktop\privatekey.txt ?



Alexandre Naverniouk

**Comment by Jnkz** [comment]
Ok sure, was stupid i forget that. The program is running, thank's you so much, let's try to get my password now!

**Comment by Jnkz** [comment]
Hey back. The program is working great. I just wanna know if there is a way to speed up it. I'm running this and i have to check like 500 billions of password, the program is going fast 250 milions 13 minutes, but my pc is not doing too much on it.  "Only" 20% of my cpu is working on it. Is that normal? Can i speed it up?

**Comment by lexansoft** [comment]
500 billion ;)

You need to work on your template file to reduce the number of possible
combinations.

You should understand that if anyone could test 500 billion combinations on
a home computer then all the passwords will be not secure.






Alexandre Naverniouk
