### ISSUE TITLE
Does this work for PRE-SALE wallets?

### ISSUE THREAD

**Issue by AndyNormore** [lexansoft/ethcracker#6]
I've just found out that pre-sale wallets are particularly difficult to work with.

Can any one verify for a fact this software works on Pre-Sale wallets?

**Comment by lexansoft** [comment]
yes


Alexandre Naverniouk

**Comment by AndyNormore** [comment]
Thanks for the quick reply. Would you mind updating the Readme? There's a bunch of us fools who have forgotten, and need special attention for the pre-sale wallets... 

not sure if you are aware, but Mist crashes a lot importing pre-sale wallets, and we're all in a panic. :)

Thanks for confirming presale... Do you have a cracking service? :)

**Comment by lexansoft** [comment]
I do not provide cracking service. And I would not recommend using any.  Do
not trust your private key to anyone.


Alexandre Naverniouk

**Comment by AndyNormore** [comment]
Thanks for the tip, but 0% of 0 is 0. :(

249 Ethereum down the draaaaaaaaaaaaaaaaaaaaaain. Your software is great, thanks a lot. I'll have it running for the next year... 

Does this run on the GPU at all, or just CPU cores? 

(again maybe just a little more docs would help so many people enjoy your software so much more :)

**Comment by lexansoft** [comment]
CPU only.


Alexandre Naverniouk

**Comment by AndyNormore** [comment]
Thank you, Cheers

**Comment by lexansoft** [comment]
fyi

We have an active Gitter channel. It might be useful for you to join.

People share there some tips and help each other.

https://gitter.im/lexansoft/ethcracker


Alexandre Naverniouk
