### ISSUE TITLE
Script doesn't finish? 73% 

### ISSUE THREAD

**Issue by AndyNormore** [lexansoft/ethcracker#7]
![image](https://user-images.githubusercontent.com/1661561/27002956-8f7af3c4-4dbb-11e7-9fca-c2c565ce1a44.png)

My screen shot shows the script finishing at 73%.

Is this really happening or just bad output?

**Comment by lexansoft** [comment]
If you have password length restrictions, then too long or too short
variants are just skipped. So the total number of variants are less than
the theoretical maximum.


Alexandre Naverniouk

**Comment by AndyNormore** [comment]
Excellent, thank you. It's running 8-20 by default I think.

But some combos would end up being REALLY long, thus skipping. Cheers.
