### ISSUE TITLE
Stops suddenly

### ISSUE THREAD

**Issue by Nozu82** [lexansoft/ethcracker#8]
Script just stops suddenly everytime. (Password guess charactes replaced with *)

Output:
TH1-> #436/2977 14% Left: 30m53.346102035s ****** ***** ***
TH1-> #437/2977 14% Left: 30m55.046743002s ***** ***** ******
:-( Sorry... password not found

I tried to add -start_from 435 but then it goes through only couple of options and stops at the same point.

**Comment by lexansoft** [comment]
If you have length restrictions, then a lot of variants are skipped and the
actual number of the possible variants is less than the theoretical
estimation.


Alexandre Naverniouk
