### ISSUE TITLE
Request / suggestion?

### ISSUE THREAD

**Issue by Nozu82** [lexansoft/ethcracker#9]
Hi,

Would it be possible to do an option that the program would try given words in specific order?
I believe my lost password _might_ be in format: "word1_word2_word3 !"

There are few different options how I might have spelled the words combined with numbers and there might be underscores or spaces. So I have quite some options.

But trying to figure out how to config this program so that I would have as little combinations to try as possible.

So instead of doing this kind of options for every single word option (current version): 
word1 word1! _word1! _word1_ \sword1\s \sword1\s! _word1_! \sword1_! _word1\s!

...and repeat same kind of line for each possible word option.

I'd suggest an option to give specific orders like:

1st possible part: 'word1', 'word2', 'word3'
2nd possible part: '_', ' ' (*underscore and space)
3rd possible part: 'word1', 'word2', 'word3'
4th possible part: '_!', '!', ' !' (*underscore, space and exclamation marks combined differently)
5th possible ...
6th possible ...

This would make configuring more simple and less prone to user errors. But most of all this would leave lots of useless combinations away that are known from the start that they won't work. But hey, I'm not a programmer. Is this something that could be easily added to options that this program could offer?

**Comment by lexansoft** [comment]
You can use key -keep_order . It does exactly that ;)


Alexandre Naverniouk

**Comment by Nozu82** [comment]
Nice, thanks! I have read the Readme file but apparently I need to practise my reading... Well ok, I probably just didn't understand what I had read. :)

My couple of first passes hasn't been fruitful. I've added a few more words to the mix and as you know the time required is getting exponentially higher with every word added. Which gives me a new idea for suggestion! (I'm full of ideas lately aren't I? :) Possibly you'll tell me that even this is already possible. :)

Since with each added word with re-run, the program starts from the beginning. Even trying those combinations already tried in the previous run. I suppose the program creates at first all the possible combinations and then starts to run those one by one. Would it be possible to give a command that the program would only export all those combinations in a separate text file. Then when starting a program give a refer to that file so it would "skip" those tried combinations. Kind of like a log file of "already tried" -options. I think it would fasten cracking up quite a bit.

Luckily I don't have much Ether in my wallet... Or shame that it doesn't have more if I get it open! :D

**Comment by anormore** [comment]
Hey @lexansoft loving your program, learning all the tricks of it now. Running half a billion passwords now lol.

I just realized how much more efficient this setting will make password generation for me. 

Think we could get -start_from 10% 20% 30% and so on?

I'm currently having to stop my terminal, manually divide numbers out, run a new console, put that number in. Repeat this process 20 times. Would be nice just say "Start new process from 33%"

Please? :)

**Comment by lexansoft** [comment]
It would be a nice feature. I will implement it in the next version.




Alexandre Naverniouk

**Comment by lexansoft** [comment]
The % feature is done

**Comment by anormore** [comment]
Sorry to resurrect the dead, can we get an 'end at %' as well? This way I can set 3 CPU's to 
0-33
34-66
67-100

Or more simply
0-33
33-66
66-100
